version: "3.9"

services:
  db:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./wait-for-it.sh db:3306 -- sh entrypoint.sh
    volumes:
      - .:/app
      - bundle-data:/bundle
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  mysql-data:
  bundle-data:
