default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  socket: <%= ENV['DB_SOCKET'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>


production:
  <<: *default
  database: anki_production
  username: anki
  password: <%= ENV["ANKI_DATABASE_PASSWORD"] %>
