name: ANKI CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build_prepare:
    runs-on: ubuntu-latest
    container: 
      image: sunci/ruby:3.2.2
    steps:
      - uses: actions/checkout@v2
      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: vendor-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            vendor-${{ runner.os }}-
      - name: Bundle Install
        run: |
          cp config/database.example.yml config/database.yml
          bundle install --path vendor/bundle
  test_rubocop:
    needs: build_prepare
    runs-on: ubuntu-latest
    container: 
      image: sunci/ruby:3.2.2
    steps:
      - uses: actions/checkout@v2
      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: vendor-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            vendor-${{ runner.os }}-
      - name: Rubocop Lint
        run: |
          bundle install --path vendor/bundle
          bundle exec rubocop --require rubocop/formatter/checkstyle_formatter --format RuboCop::Formatter::CheckstyleFormatter --no-color app/ lib/
