name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build_prepare:
    runs-on: ubuntu-latest
    container: 
      image: sunci/ruby:3.2.2
    steps:
      - uses: actions/checkout@v2
      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: vendor-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            vendor-${{ runner.os }}-
      - name: Bundle Install
        run: |
          cp config/database.example.yml config/database.yml
          bundle install --path vendor/bundle
  test_rspec:
    needs: build_prepare
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7.22
        env:
          MYSQL_DATABASE: db-test
          MYSQL_USER: user-test
          MYSQL_PASSWORD: password-test
          MYSQL_ROOT_PASSWORD: password-test
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: vendor-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            vendor-${{ runner.os }}-
      - name: Setup Database and Run Tests
        run: |
          bundle install --path vendor/bundle
          RAILS_ENV=test bundle exec rails db:drop db:create db:migrate
          bundle exec rspec
  test_rubocop:
    needs: build_prepare
    runs-on: ubuntu-latest
    container: 
      image: sunci/ruby:3.2.2
    steps:
      - uses: actions/checkout@v2
      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: vendor-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            vendor-${{ runner.os }}-
      - name: RuboCop Lint
        run: |
          bundle install --path vendor/bundle
          bundle exec rubocop --require rubocop/formatter/checkstyle_formatter --format RuboCop::Formatter::CheckstyleFormatter --no-color app/ lib/
